local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("storage") %>  

amazon:
  service: Disk
  root: <%= Rails.root.join("storage") %>

dropbox:
  service: Dropbox
  access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>  